"""Formatting helpers for UI rendering and markdown export."""

from __future__ import annotations

from schemas.workflow_models import FinalReport


def to_markdown(report: FinalReport) -> str:
    lines = [
        "# AI Business Workflow Analyst Report",
        "",
        "## 1) Executive Snapshot",
        report.executive_summary.strip(),
        "",
        "### Recommended Action Items",
        "- **Appoint an executive sponsor** to own the 90-day AI initiative and KPI tracking.",
        "- **Launch one quick-win pilot** with clear success metrics and weekly reporting.",
        "- **Confirm data readiness and governance** before scale-up to reduce implementation risk.",
        "",
        "### Opportunity-at-a-Glance",
        "| Area | Current State | AI Opportunity | Business Outcome |",
        "|---|---|---|---|",
        "| Front-office workflows | Manual and repetitive tasks | AI-assisted triage/copilot | Faster response times |",
        "| Internal operations | Fragmented knowledge/processes | Workflow automation + knowledge assistant | Lower cycle time |",
        "| Decision support | Limited real-time visibility | KPI instrumentation + alerts | Better execution control |",
        "",
        "## 2) Business Context",
        "### Company Overview",
        report.company_overview.strip(),
        "",
        "### Products / Services",
        report.products_services.strip(),
        "",
        "### Target Market",
        report.target_market.strip(),
        "",
        "### Market Positioning",
        report.market_positioning.strip(),
        "",
        "## 3) Key Insights & Risk Areas",
        "### Overlooked Signals / Non-Obvious Insights",
        report.overlooked_signals.strip(),
        "",
        "### Likely Operational Bottlenecks",
        report.likely_operational_bottlenecks.strip(),
        "",
        "## 4) AI Opportunity Map",
        report.ai_automation_opportunities.strip(),
        "",
        "### Process Diagram (Current → Future)",
        "```mermaid",
        "flowchart LR",
        "    A[Manual Intake & Routing] --> B[AI Triage + Classification]",
        "    B --> C[Human Review on Exceptions]",
        "    C --> D[Automated Follow-Up + Tracking]",
        "    D --> E[KPI Dashboard for Leaders]",
        "```",
        "",
        "## 5) 90-Day Implementation Roadmap",
        report.prioritized_ai_roadmap.strip(),
        "",
        "### Timeline Chart",
        "```mermaid",
        "gantt",
        "    title 90-Day AI Roadmap",
        "    dateFormat  YYYY-MM-DD",
        "    section Phase 1",
        "    Baseline KPIs & Scope :a1, 2026-01-01, 30d",
        "    section Phase 2",
        "    Pilot Launch & Iterate :a2, after a1, 30d",
        "    section Phase 3",
        "    Production Hardening :a3, after a2, 30d",
        "```",
        "",
        "## 6) Suggested Engagement Angle",
        report.suggested_engagement_angle.strip(),
        "",
    ]

    disclaimer = report.disclaimer.strip().replace("as of 2025", "as of 2026")
    lines.extend(["---", f"*{disclaimer}*"])
    return "\n".join(lines)
